version: '1'

services:
  mysql-standalone1:
    image: mysql:8.0
    environment:
    - MYSQL_ROOT_PASSWORD=admin 
    - MYSQL_DATABASE=forum
    - MYSQL_USER=testuser 
    - MYSQL_PASSWORD=testuser123
  springboot-docker-container:
   image: adriano/forum
   ports:
     - 8083:8083
   build:
     context: ./
     dockerfile: Dockerfile
   depends_on:
     - mysql-standalone1      